---
#
# Ametrine Configuration
# Theme Configuration
#

# Choose if you want to run the before
# commands in the main configuration.
usemainprecmds: False

# Choose if you want to run the after
# commands in the main configuration.
usemainaftercmds: False

# Commands run before changing the theme, these
# are theme specific.
precmds: 
    - echo -e "Precommand for theme 2.\nPrecommands from main config disabled"

# Commands run after changing the theme, these
# are theme specific.
aftercmds: 
    - echo -e "Aftercommands for theme 2\nAftercommands from main config disabled"
