---
#
# Ametrine Configuration
# Main Configuration
#

# The location of where your themes are
# stored. Supports use of ~ to act as home.
themepath: "~/themes"

# Dangerous! Enable overwriting of real files
# with symlinks. (only replaces symlinks if false)
overwritefiles: False

# Commands run before changing the theme, these
# are the default. Themes can also choose to 
# define their own.
precmds: 
#    - killall waybar # Restart waybar with new theme


# Commands run after changing the theme, these
# are the default. Themes can also choose to 
# define their own.
aftercmds: 
#    - waybar & # Start up waybar with new theme
