---
#
# Ametrine Configuration
# Theme Configuration
#

# Choose if you want to run the before
# commands in the main configuration.
usemainprecmds: True

# Choose if you want to run the after
# commands in the main configuration.
usemainaftercmds: True

# Commands run before changing the theme, these
# are theme specific.
precmds: 
    - echo "Precommand for theme 3. Precommands from main config enabled, shouldn't run as base theme."

# Commands run after changing the theme, these
# are theme specific.
aftercmds: 
    - echo "Aftercommands for theme 3. Aftercommands from main config enabled, shouldn't run as base theme."
