name: Build Ametrine
on: [push, pull_request, workflow_dispatch]
jobs:
  buildametrine:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build Ametrine
      run: |
        cd src
        nix-build -o ./result

    - name: Ametrine version
      run: ./result/bin/ametrine --version
