name: Build Ametrine
on: [push, pull_request, workflow_dispatch]
jobs:
  buildametrine:
    runs-on: ubuntu-latest
    steps:
    - name: Build Ametrine
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: cd src
    - run: nix-build

    - name: Ametrine version
    - run: ./result/bin/ametrine --version
