name: "Build Ametrine"
on:
  pull_request:
  push:
jobs:
  buildametrine:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build Ametrine
    - run: |
        cd src
        nix-build

    - name: Ametrine version
    - run: ./result/bin/ametrine --version
