name: Build Ametrine
on: [push, pull_request, workflow_dispatch]
jobs:
  buildametrine:
    runs-on: ubuntu-latest
    env:
      XDG_CONFIG_HOME: "$HOME/.config"
      DEBUG: 1
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Install required packages
      run: pip install build setuptools

    - name: Build Ametrine
      run: |
        cd src
        python -m build
        pip install dist/*.whl

    - name: Copy testing themes
      run: |
        mkdir $HOME/themes
        mkdir $HOME/.config/ametrine
        cp src/github/workflows/themes/* $HOME/themes -r 
        cp src/github/workflows/config.yaml $HOME/.config/ametrine/

    - name: Ametrine version
      run: ametrine --version

    - name: Theme switching
      run: |
        ametrine change 1
        ametrine change 2

    - name: Theme cleanup
      run: ametrine cleanup all

    - name: Theme subcommands
      run: |
        ametrine theme config
        ametrine theme ls
